### ISSUE TITLE
Compiling problems, can't find log-core

### ISSUE THREAD

**Issue by b4ll** [maddinat0r/samp-discord-connector#104]
Hi, I try to compile discord-connector plugin on my own, but got stuck at log-core plugin. I tried everything, downloading it as root, as normal user, include it into samp-discord-connector directory, setting `CMAKE_PREFIX_PATH` but no progress.

I try to build it with command `cmake -DCMAKE_PREFIX_PATH=/home/samp/samp-log-core ..`

```
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.1t") 
-- Version: 5.3.0
-- Build type:
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Success
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Success
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Success
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Looking for open
-- Looking for open - found
CMake Error at CMakeLists.txt:39 (find_package):
  Could not find a package configuration file provided by "log-core" with any
  of the following names:
```

```

    log-coreConfig.cmake
    log-core-config.cmake
```

`
  Add the installation prefix of "log-core" to CMAKE_PREFIX_PATH or set
  "log-core_DIR" to a directory containing one of the above files.  If
  "log-core" provides a separate development package or SDK, be sure it has
  been installed.
`

log-core directory is at `/home/samp/samp-log-core`

I am really new to plugin compilation, what I am doing wrong? System is Debian 8.

**Comment by maddinat0r** [comment]
CMake is kinda weird in this regard; you actually have to specify the `cmake` folder within the log-core directory, i.e. `/home/samp/samp-log-core/cmake`. Also make sure you're using the correct log-core package ([that one](https://github.com/maddinat0r/samp-log-core/releases/download/v0.5/samp-log-core-v0.5-Linux.tar.gz)), not the log-core source code or the runtime package.

**Comment by b4ll** [comment]
Thanks for the reply. Now CMake found log-core package, but throws out another error

`CMake Error at CMakeLists.txt:39 (find_package):
  Could not find a configuration file for package "log-core" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /home/samp/samp-log-core-v0.5-Linux/cmake/log-coreConfig.cmake, version: v0.5 (64bit)`

I have 32 bit system, is that causing the issue? Is it better to compile plugins on 32 or 64 bit system?

**Comment by maddinat0r** [comment]
No, the problem isn't on your side. You actually have to use 32bit, as the SA:MP server itself is a 32bit executable and thus will accept only 32bit libraries/plugins.
The actual problem was caused by a misconfiguration of the automated build system (I passed a compile option at the wrong place). I've fixed it in maddinat0r/samp-log-core@dba06936c07affcb2f4e8e009588110f5f0bdfa0 (and did some other minor fixes) and will release v0.5.1 ASAP.

**Comment by maddinat0r** [comment]
I've just [released v0.5.1](https://github.com/maddinat0r/samp-log-core/releases/tag/v0.5.1). Please try it out again.

**Comment by b4ll** [comment]
Okay, I compiled discord-connector plugin successfully (file weight is 8MB though), but now I need to compile log-core plugin also. I tried to build it like discord plugin because there is no build instruction, but I got stuck again. CMake can't find yaml-cpp package configuration. I downloaded a repository from [here](https://github.com/jbeder/yaml-cpp) but it still can't find config file. Build command

`cmake -DCMAKE_PREFIX_PATH=/home/samp/yaml-cpp-yaml-cpp-0.6.3 ..`

`CMake Error at CMakeLists.txt:33 (find_package):
  Could not find a package configuration file provided by "yaml-cpp" with any
  of the following names:

    yaml-cppConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "yaml-cpp" to CMAKE_PREFIX_PATH or set
  "yaml-cpp_DIR" to a directory containing one of the above files.  If
  "yaml-cpp" provides a separate development package or SDK, be sure it has
  been installed.`

I checked directory `yaml-cpp-yaml-cpp-0.6.3` and there is `yaml-cpp-config.cmake.in` file. Do I have to compile/install yaml first or something else? I also tried install  libyaml-cpp-dev with ` sudo apt-get install libyaml-cpp-dev` but nothing changed.

**Comment by maddinat0r** [comment]
You're not that far off. Take a look at the [CI config file](https://github.com/maddinat0r/samp-log-core/blob/master/appveyor.yml), there are all commands you should need to build yaml-cpp and log-core. Make sure you replace all variables (all `$env:NAME` variables and `@CMAKE_ARGS`) with the proper values.

**Comment by b4ll** [comment]
After hours of attempts, I compiled log-core plugin, but server crashes on start with discord-connector and log-core plugins of my build. Logs:

`[21:04:53]  Loading plugin: crashdetect.so
[21:04:53]   CrashDetect plugin 4.19.4
[21:04:53]   Loaded.
[21:04:53]  Loading plugin: discord-connector.so
[21:04:53] [debug] Server crashed due to an unknown error
[21:04:53] [debug] Native backtrace:
[21:04:53] [debug] #0 f73d68b6 in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () in plugins/crashdetect.so
[21:04:53] [debug] #1 f73ce120 in _ZN18CrashDetectHandler20PrintNativeBacktraceERSoRKN2os7ContextE () in plugins/crashdetect.so
[21:04:53] [debug] #2 f73ce886 in _ZN18CrashDetectHandler20PrintNativeBacktraceERKN2os7ContextE () in plugins/crashdetect.so
[21:04:53] [debug] #3 f73cef96 in _ZN18CrashDetectHandler7OnCrashERKN2os7ContextE () in plugins/crashdetect.so
[21:04:53] [debug] #4 f73d5f82 in ?? () in plugins/crashdetect.so
[21:04:53] [debug] #5 f7734cc0 in __kernel_rt_sigreturn () in linux-gate.so.1
[21:04:53] [debug] #6 f7734c99 in __kernel_vsyscall () in linux-gate.so.1
[21:04:53] [debug] #7 f742d367 in gsignal () in /lib/i386-linux-gnu/i686/cmov/libc.so.6
[21:04:53] [debug] #8 f742ea23 in abort () in /lib/i386-linux-gnu/i686/cmov/libc.so.6
[21:04:53] [debug] #9 f765ba55 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv () in /usr/lib/i386-linux-gnu/libstdc++.so.6
[21:04:53] [debug] #10 f7659733 in ?? () in /usr/lib/i386-linux-gnu/libstdc++.so.6
[21:04:53] [debug] #11 f76597ad in ?? () in /usr/lib/i386-linux-gnu/libstdc++.so.6
[21:04:53] [debug] #12 f7659aa0 in __cxa_rethrow () in /usr/lib/i386-linux-gnu/libstdc++.so.6
[21:04:53] [debug] #13 f6f88a96 in _ZN4YAML8LoadFileERKSs () in log-core2.so
[21:04:53] [debug] #14 f6f43647 in ?? () in log-core2.so
[21:04:53] [debug] #15 f6f4504d in ?? () in log-core2.so
[21:04:53] [debug] #16 f6f26ff0 in samplog_GetApi () in log-core2.so
[21:04:53] [debug] #17 f70e78f8 in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #18 f70e785b in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #19 f70e78d6 in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #20 f70e7a3e in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #21 f70e7ff9 in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #22 f70ea857 in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #23 f7146c59 in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #24 f720f033 in ?? () in plugins/discord-connector.so
[21:04:53] [debug] #25 f720f341 in Load () in plugins/discord-connector.so
[21:04:53] [debug] #26 080d2772 in ?? () in ./samp03svr
[21:04:53] [debug] #27 080d2b2a in ?? () in ./samp03svr
[21:04:53] [debug] #28 080aa100 in ?? () in ./samp03svr
[21:04:53] [debug] #29 f7418a63 in __libc_start_main () in /lib/i386-linux-gnu/i686/cmov/libc.so.6
[21:04:53] [debug] Registers:
[21:04:53] [debug] EAX: 00000000 EBX: 00000719 ECX: 00000719 EDX: 00000006
[21:04:53] [debug] ESI: 0895d464 EDI: f75a8000 EBP: fff55668 ESP: fff554e4
[21:04:53] [debug] EIP: f7734c99 EFLAGS: 00200206
[21:04:53] [debug] Stack:
[21:04:53] [debug] ESP+00000000: fff55668 00000006 00000719 f742d367
[21:04:53] [debug] ESP+00000020: fff55514 00000000 f73fe220 00000001
[21:04:53] [debug] ESP+00000040: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+00000060: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+00000080: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+000000a0: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+000000c0: f7757000 f7701000 00000001 fff55610
[21:04:53] [debug] ESP+000000e0: 00000001 00000000 f76f93d0 00000000
[21:04:53] [debug] ESP+00000100: f7614af8 f76f898c 081a29ec fff55668
[21:04:53] [debug] ESP+00000120: f76f9000 0895d464 081a29ec fff55668
[21:04:53] [debug] ESP+00000140: f76f9000 081a29ec f765ba55 00000001
[21:04:53] [debug] ESP+00000160: f7757000 fff55664 00000000 f76238b8
[21:04:53] [debug] ESP+00000180: f6fc310c fff557f8 f7659733 0895d418
[21:04:53] [debug] ESP+000001a0: f774a6e0 f7659775 f76597a4 00000000
[21:04:53] [debug] ESP+000001c0: f7701000 f7659775 f7659a71 0895d438
[21:04:53] [debug] ESP+000001e0: f6fc310c f6f83bd2 f6eb00c4 fff55738
[21:04:53] [debug] ESP+00000200: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+00000220: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+00000240: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+00000260: 00000000 00000000 00000000 f6eb4a00
[21:04:53] [debug] ESP+00000280: 00000000 f76f8420 00000006 00000000
[21:04:53] [debug] ESP+000002a0: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+000002c0: 00000000 00000000 00000000 00000000
[21:04:53] [debug] ESP+000002e0: 00000000 00000000 00000008 fff5578c
[21:04:53] [debug] ESP+00000300: f7700080 f7700058 f7700060 f700489c
[21:04:53] [debug] ESP+00000320: f70067f8 8f1bbcdc f6f43619 ca62c1d6
[21:04:53] [debug] ESP+00000340: 5a827999 5a827999 5a827999 00010203
[21:04:53] [debug] ESP+00000360: 0895cad4 0895cad4 fff5587c 00000064
[21:04:53] [debug] ESP+00000380: f73b0774 f6e22000 f6ca5780 00000064
[21:04:53] [debug] ESP+000003a0: f6e22000 f75a8420 00000014 f7406c38
[21:04:53] [debug] ESP+000003c0: 00000001 081a2a9c 00000000 00000000
[21:04:53] [debug] ESP+000003e0: f773efbd f770581e f70bf0e0 f7403dc8
[21:04:53] [debug] Loaded modules:
[21:04:53] [debug] 00000000 - 00188003 samp03svr
[21:04:53] [debug] f7734000 - f7734e36 linux-gate.so.1
[21:04:53] [debug] f771e000 - f772081b /lib/i386-linux-gnu/i686/cmov/libdl.so.2
[21:04:53] [debug] f7702000 - f771cd2b /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
[21:04:53] [debug] f760f000 - f7708d0e /usr/lib/i386-linux-gnu/libstdc++.so.6
[21:04:53] [debug] f75c9000 - f760db43 /lib/i386-linux-gnu/i686/cmov/libm.so.6
[21:04:53] [debug] f75ac000 - f75c83c4 /lib/i386-linux-gnu/libgcc_s.so.1
[21:04:53] [debug] f73ff000 - f75b422f /lib/i386-linux-gnu/i686/cmov/libc.so.6
[21:04:53] [debug] f7736000 - f7756d6c /lib/ld-linux.so.2
[21:04:53] [debug] f73b7000 - f73fb3ac plugins/crashdetect.so
[21:04:53] [debug] f7008000 - f73d4b80 plugins/discord-connector.so
[21:04:53] [debug] f6e9a000 - f70063c9 log-core2.so
[21:04:53] [debug] f6e2e000 - f6e8e254 /usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.0
[21:04:53] [debug] f7726000 - f772d09f /lib/i386-linux-gnu/i686/cmov/librt.so.1
[21:04:53] [debug] f6c61000 - f6e44b2c /usr/lib/i386-linux-gnu/i686/cmov/libcrypto.so.1.0.0`

Is there a way to build it as static plugin? Then it would be more comptatible I think.

**Comment by maddinat0r** [comment]
I can't say why exactly it crashed, as I don't know how you built both libraries or/and what modifications you did to the source code. The only real change I did to the v0.5.1 log-core update is to link the runtime statically to the library. This could maybe cause the crash, but I can't say that for sure (didn't have the time to test it yet).

What do you mean by
> build it as static plugin  

? If you're talking about linking the log-core statically into the plugin, then no. The whole reason behind the log-core utility library is to have a central point of logging. Linking it statically would entirely destroy that and mess with other things (like crash detection).

**Comment by maddinat0r** [comment]
Can you describe your setup in more detail? What exactly did you compile yourself, the log-core utility, the plugin, or both? What versions are you using? log-core v0.5.1 is linking the runtime statically, so that error shouldn't happen.

**Comment by b4ll** [comment]
All commands one by one

`git clone --recursive https://github.com/maddinat0r/samp-discord-connector
cd samp-discord-connector 
git submodule update --init --recursive
sudo dpkg --add-architecture i386
sudo apt-get -qq update
sudo apt-get -qq -y install g++-multilib gcc-multilib

wget -q "https://github.com/maddinat0r/samp-log-core/releases/download/v0.5.1/samp-log-core-v0.5.1-Linux.tar.gz" -O samp-log-core.tar.gz
mkdir -p samp-log-core && tar zfx samp-log-core.tar.gz -C samp-log-core --strip-components=1
export LOGCORE_DIR="samp-log-core/cmake"
cmake -DCMAKE_PREFIX_PATH=/home/samp/samp-log-core/cmake -DOPENSSL_SSL_LIBRARY="/usr/lib/i386-linux-gnu/libssl.so" -DOPENSSL_CRYPTO_LIBRARY="/usr/lib/i386-linux-gnu/libcrypto.so" -S . -B build || true`

**Comment by b4ll** [comment]
Okay, I have realized that I had only compiled discord-plugin, that is why error was in log-core plugin. After log-core compilation, there is no further progress. The server crashes on start as before, even with `@CMAKE_ARGS` set and other environment variables. I tried thousand times, I don't know what I am doing wrong.

```
git clone -q --branch=master https://github.com/maddinat0r/samp-log-core.git
git checkout -qf 50dcaa757998b4e4f53c168829b207a162106b64
GIT_REPO_VERSION="$(git describe --tags --always)"
git submodule update --init --recursive
sudo apt-get -qq update
sudo apt-get -qq -y install g++-multilib gcc-multilib
CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32"

git clone --quiet https://github.com/jbeder/yaml-cpp.git yaml-cpp
git -C yaml-cpp checkout tags/yaml-cpp-0.6.3
BUILD_TYPE="Release"
cmake -Wno-dev --no-warn-unused-cli -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_INSTALL_PREFIX=yaml-cpp-install -DYAML_CPP_BUILD_CONTRIB=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_TESTS=OFF -DBUILD_GMOCK=OFF -DYAML_MSVC_SHARED_RT=OFF "$CMAKE_ARGS" -S yaml-cpp -B yaml-cpp-build
cmake --build yaml-cpp-build --config "$BUILD_TYPE" --target install

cd samp-log-core
cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -Dyaml-cpp_DIR=/home/samp/yaml-cpp-install/share/cmake/yaml-cpp -DLOGCORE_VERSION="$GIT_REPO_VERSION" -DLOGCORE_INSTALL_DEV=OFF "$CMAKE_ARGS" -S . -B build
cmake --build build --target package --config "$BUILD_TYPE"
```

I don't know if my environment variables are set correctly, because you set it like

```
$env:GIT_REPO_VERSION = "$(git describe --tags --always)"
$CMAKE_ARGS = "-DCMAKE_CXX_FLAGS=-m32", "-DCMAKE_C_FLAGS=-m32"
```

These commands give me errors `-bash: :GIT_REPO_VERSION: command not found` so I set it like this

```
GIT_REPO_VERSION="$(git describe --tags --always)"
CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32"
```

The syntax differs because of your system and my system or I am doing it wrong?

**Comment by maddinat0r** [comment]
The syntax is indeed partly different, because AppVeyor emphasizes PowerShell, so my config files also often use PowerShell instead of bash.
Try running these commands to compile log-core and DCC (make sure to set the `BOOST_ROOT` environment variable correctly):
```sh
# log-core
git clone --recursive https://github.com/maddinat0r/samp-log-core.git

sudo apt-get -qq update
sudo apt-get -qq -y install g++-multilib gcc-multilib

git clone --quiet https://github.com/jbeder/yaml-cpp.git yaml-cpp
git -C yaml-cpp checkout tags/yaml-cpp-0.6.3
BUILD_TYPE="Release"
cmake -Wno-dev --no-warn-unused-cli -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_INSTALL_PREFIX=yaml-cpp-install -DYAML_CPP_BUILD_CONTRIB=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_TESTS=OFF -DBUILD_GMOCK=OFF -DYAML_MSVC_SHARED_RT=OFF -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -S yaml-cpp -B yaml-cpp-build
cmake --build yaml-cpp-build --config "$BUILD_TYPE" --target install

cd samp-log-core
cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -Dyaml-cpp_DIR="../yaml-cpp-install/share/cmake/yaml-cpp" -DLOGCORE_VERSION="$GIT_REPO_VERSION" -DLOGCORE_INSTALL_DEV=OFF -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -DCMAKE_INSTALL_PREFIX=install -S . -B build
cmake --build build --target install --config "$BUILD_TYPE"
cd ..

# discord
git clone --recursive https://github.com/maddinat0r/samp-discord-connector
cd samp-discord-connector 

sudo dpkg --add-architecture i386
sudo apt-get -qq update
sudo apt-get -qq -y install g++-multilib gcc-multilib libssl-dev:i386

cmake -DOPENSSL_SSL_LIBRARY="/usr/lib/i386-linux-gnu/libssl.so" -DOPENSSL_CRYPTO_LIBRARY="/usr/lib/i386-linux-gnu/libcrypto.so" -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -DOPENSSL_ROOT_DIR="/usr" -DBOOST_ROOT="$BOOST_ROOT" -Dlog-core_DIR="samp-log-core/install/cmake" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -S . -B build
cmake --build build --config $BUILD_TYPE --target package
```
The versions will be slightly incorrect, but that's only a cosmetic issue.

**Comment by b4ll** [comment]
I had executed these commands one by one, still no luck, crash occurs. I uploaded log files from builds and a server_log file, maybe this could help, cause I have no idea what could be wrong.

[CMakeOutput-discord.log](https://github.com/maddinat0r/samp-discord-connector/files/3729277/CMakeOutput-discord.log)
[CMakeOutput-logcore.log](https://github.com/maddinat0r/samp-discord-connector/files/3729278/CMakeOutput-logcore.log)
[server_log.txt](https://github.com/maddinat0r/samp-discord-connector/files/3729279/server_log.txt)

**Comment by maddinat0r** [comment]
Can you try creating a empty file named `log-config.yml` in your server root directory and try again?

**Comment by b4ll** [comment]
I didn't know about `log-config.yml` file, but after creating that file there is no crash. However, in server log file it shows discord-plugin version as 0.2.4

`[19:26:47]  Loading plugin: discord-connector.so
[19:26:48]  >> plugin.dc-connector: 0.2.4 successfully loaded.`

Maybe it's only cosmetic issue as you stated before, cause in .inc file there are new callbacks like `DCC_OnMessageCreate` or `DCC_OnMessageDelete`. So all the pain was empty file?

**Comment by maddinat0r** [comment]
Yes, the version number is only cosmetical, you can change it by setting the CMake variable (`-DLOGCORE_VERSION=someversionnumber` for log-core and `-DDCC_VERSION=version` for DCC).
The crash with a missing log config file is a bug, which probably got introduced in log-core 0.5.1 when I updated the YAML library.

**Comment by meemk** [comment]
Visual Studio Code 2019

CMake Error at CMakeLists.txt:54 (find_package):
  Could not find a package configuration file provided by "log-core" with any
  of the following names:

    log-coreConfig.cmake
    log-core-config.cmake

  Add the installation prefix of "log-core" to CMAKE_PREFIX_PATH or set
  "log-core_DIR" to a directory containing one of the above files.  If
  "log-core" provides a separate development package or SDK, be sure it has
  been installed.
